### ISSUE TITLE
Opening Ungit on VSCode also opens a new tab on the browser to /

### ISSUE THREAD

**Issue by franky47** [Hirse/vscode-ungit#29]
## Context
- macOS 10.12.6
- VSCode 1.18.0
- vscode-ungit extension 1.1.1
- Ungit 1.2.3

## Description
When opening an ungit tab on VSCode, shortly after the focus is set on the default web browser where a new tab is opened to the address `http://localhost:8448/#/repository?path=%2F`, which points to the filesystem root (which for obvious reasons is not a git repository).

The tab opened in VSCode is correctly pointing to the workspace root.

**Comment by Hirse** [comment]
Thanks for your report.

This does not happen for me, but I am working on Windows. I will try to check with a macOS user when I have the chance.

**Comment by franky47** [comment]
FYI, I've reproduced it on a different Mac, with a fresh install of VSCode and vscode-ungit extension.

**Comment by Hirse** [comment]
Thanks.
Has this only happened with the latest version?
Could you try with the previous release:
https://github.com/Hirse/vscode-ungit/releases/tag/v1.1.0

**Comment by franky47** [comment]
I have the problem with v1.1.0 as well, but not with v1.0.6.

**Comment by Hirse** [comment]
Interesting, it might be related to https://github.com/FredrikNoren/ungit/issues/986.
Changing the ungit command to include `--no-b` could help. I can publish a version with that later, but I can't test it before.

**Comment by franky47** [comment]
Maybe I can test it on my side, anything particular required to build your extension?

**Comment by Hirse** [comment]
No, you should just be able to build it with the scripts in the `package.json`.

I have added the command and built a version, feel free to try this one:
[vscode-ungit-1.1.1.vsix.zip](https://github.com/Hirse/vscode-ungit/files/1484945/vscode-ungit-1.1.1.vsix.zip)

**Comment by franky47** [comment]
No luck with this one I'm afraid..

**Comment by Hirse** [comment]
Given that https://github.com/FredrikNoren/ungit/issues/994 got fixed, could you please see if you still have this issue with the latest version?

**Comment by franky47** [comment]
Yep, it's fixed now, thanks !

**Comment by bcroq** [comment]
This happens to me since a few days, maybe weeks.

Do I open a new issue?

vscode 1.40.0
vscode-ungit 2.1.0

**Comment by Hirse** [comment]
@bcroq Do you have a version of ungit installed globally by chance? 
If so, can you try to update that?

**Comment by bcroq** [comment]
@Hirse I didn't have ungit installed globally.

I have just installed ungit globally (version 1.5.0) then restarted vscode. Ungit is still opened in my browser (and in vscode) when I run the command "Open Ungit".

The ungit version in the browser is the same as the ungit version in vscode : 1.4.44+f03e661 so it doesn't use the globally installed ungit.

Edit: vscode-ungit v2.1.0

**Comment by bcroq** [comment]
@Hirse I have also tried using vscode-ungit from github and it still happens.

ungit v1.4.48 is opened in my browser (in vscode-ungit I don't know as the header is hidden).

To reproduce this bug, I sometime have to open more than one instance of vscode.

**Comment by bcroq** [comment]
I still get this bug. Am I the only one?

The first time I start ungit, it only opens in vscode. But the next times, it opens in my browser and in vscode.

**Comment by bcroq** [comment]
@Hirse found it!

This is an `ungit` bug, fixed in the next release : https://github.com/FredrikNoren/ungit/issues/1259
